"""Integration test of migrations/create_apply_credit_atomic.sql against a REAL (throwaway) PostgreSQL.

Starts an isolated `postgres:17` Docker container with a schema that mirrors the production column types,
installs the migration, runs plans built by services.credit_application, and checks that
  * a successful call produces the same ledger as the in-memory (compensation) executor, and
  * every injected failure rolls the WHOLE transaction back (credit, targets, usage rows, payment record).
Skipped automatically when Docker is not available. Never touches production.
"""
import json
import subprocess
import unittest
import uuid
from pathlib import Path

try:
    from tests.test_bank_payment_save import FakeLedger, _credit, _target
except ImportError:  # `unittest discover -s tests`
    from test_bank_payment_save import FakeLedger, _credit, _target

MIGRATION = Path(__file__).resolve().parent.parent / "migrations" / "create_apply_credit_atomic.sql"

SCHEMA = """
create role anon nologin; create role authenticated nologin; create role service_role nologin;
create table invoices (
    id integer generated by default as identity primary key, invoice_number text, project_name text,
    maintenance_year text, payment_amount numeric, cameras_number integer, payment_date date, paid text,
    year integer, description text, invoice_type text, for_month text, sent_at text, source_type text,
    source_purchase_order_id uuid, auto_created boolean default false, auto_created_at timestamptz, send_status text);
create table bank_payments (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    payment_date date, invoice_number text, source_name text, source_kind text, payment_fingerprint text unique,
    instructed_amount numeric(12,2), received_amount numeric(12,2), applied_amount numeric(12,2),
    fee_amount numeric(12,2), currency text not null default 'EUR', raw_text text,
    parsed_payload jsonb not null default '{}'::jsonb, notes text, pdf_storage_bucket text, pdf_storage_path text);
create table bank_payment_allocations (
    id bigint generated by default as identity primary key,
    payment_id bigint not null references bank_payments(id) on delete cascade,
    invoice_row_id bigint, invoice_number bigint, project_name text, maintenance_year text, year integer,
    amount_applied numeric(12,2), created_at timestamptz not null default timezone('utc', now()));
"""


def _docker_ready() -> bool:
    try:
        return subprocess.run(["docker", "info"], capture_output=True, timeout=30).returncode == 0
    except (OSError, subprocess.TimeoutExpired):
        return False


@unittest.skipUnless(_docker_ready(), "Docker is not available")
class TestApplyCreditAtomicSql(unittest.TestCase):
    container = ""

    @classmethod
    def setUpClass(cls):
        cls.container = f"caddy-sql-test-{uuid.uuid4().hex[:8]}"
        started = subprocess.run(
            ["docker", "run", "-d", "--rm", "--name", cls.container, "-e", "POSTGRES_PASSWORD=test", "postgres:17"],
            capture_output=True, text=True, timeout=900,
        )
        if started.returncode != 0:
            raise unittest.SkipTest(f"could not start postgres container: {started.stderr[:200]}")
        for _ in range(60):  # the image restarts the server once after initdb; wait for TCP
            probe = subprocess.run(
                ["docker", "exec", cls.container, "psql", "-h", "127.0.0.1", "-U", "postgres", "-c", "select 1"],
                capture_output=True, text=True,
            )
            if probe.returncode == 0:
                break
            subprocess.run(["docker", "exec", cls.container, "sleep", "1"], capture_output=True)
        else:
            cls.tearDownClass()
            raise unittest.SkipTest("postgres container did not become ready")
        cls.sql(SCHEMA)
        cls.sql(MIGRATION.read_text(encoding="utf-8"))

    @classmethod
    def tearDownClass(cls):
        if cls.container:
            subprocess.run(["docker", "rm", "-f", cls.container], capture_output=True, timeout=60)

    @classmethod
    def sql(cls, statement: str) -> str:
        done = subprocess.run(
            ["docker", "exec", "-i", cls.container, "psql", "-h", "127.0.0.1", "-U", "postgres",
             "-v", "ON_ERROR_STOP=1", "-At", "-f", "-"],
            input=statement, capture_output=True, text=True, encoding="utf-8", timeout=120,
        )
        if done.returncode != 0:
            raise RuntimeError(done.stderr.strip())
        return done.stdout.strip()

    # -- helpers ---------------------------------------------------------------------------------------
    def seed(self, ledger):
        self.sql("truncate invoices, bank_payments restart identity cascade;")
        values = []
        for r in ledger.rows.values():
            def lit(v):
                return "null" if v is None else "'" + str(v).replace("'", "''") + "'"
            values.append(
                f"({r['id']}, {lit(r['invoice_number'])}, {lit(r['project_name'])}, {lit(r['maintenance_year'])}, "
                f"{r['payment_amount']}, {lit(r['paid'])}, {r['year']}, {lit(r.get('description'))}, null)"
            )
        self.sql(
            "insert into invoices (id, invoice_number, project_name, maintenance_year, payment_amount, paid, year,"
            " description, payment_date) overriding system value values " + ",".join(values) + ";"
            " select setval(pg_get_serial_sequence('invoices','id'), 1000);"
        )

    def snapshot(self):
        return json.loads(self.sql(
            "select jsonb_build_object("
            " 'invoices', (select coalesce(jsonb_agg(to_jsonb(t) order by id), '[]') from invoices t),"
            " 'payments', (select count(*) from bank_payments),"
            " 'allocations', (select count(*) from bank_payment_allocations));"
        ))

    def call(self, payload):
        return self.sql(f"select public.apply_credit_atomic($plan${json.dumps(payload)}$plan$::jsonb);")

    @staticmethod
    def _norm(rows):
        def norm(r):
            date = r.get("payment_date")
            return (
                None if r.get("invoice_number") is None else str(r["invoice_number"]), r["project_name"],
                r["maintenance_year"], float(r["payment_amount"]), r["paid"],
                date.isoformat() if hasattr(date, "isoformat") else date, r.get("year"), r.get("description"),
            )
        return sorted((norm(r) for r in rows), key=repr)

    def assert_rolled_back(self, ledger, mutate):
        """Run a plan broken by ``mutate`` and require the DB to be identical to before."""
        self.seed(ledger)
        before = self.snapshot()
        plan = ledger.plan(8700)
        payload = json.loads(json.dumps(plan.rpc_payload()))
        mutate(payload["ops"])
        with self.assertRaises(RuntimeError):
            self.call(payload)
        self.assertEqual(self.snapshot(), before, "the failed call must leave NOTHING behind")

    # -- tests -----------------------------------------------------------------------------------------
    def test_success_matches_the_in_memory_executor(self):
        scenarios = {
            "simple": [_credit(1, -1000.0), _target(2, 130.0)],
            "multi-credit partial target": [_credit(1, -100.0), _credit(2, -50.0), _credit(3, -200.0), _target(10, 220.0), _target(11, 60.0)],
            "target only partly funded": [_credit(1, -100.0), _target(2, 130.0)],
        }
        for name, rows in scenarios.items():
            with self.subTest(name):
                ledger = FakeLedger(rows)
                self.seed(FakeLedger(rows))
                plan = ledger.plan(8700)
                self.call(plan.rpc_payload())
                db = self.snapshot()
                memory = ledger.apply(8700)
                self.assertTrue(memory.ok, memory.errors)
                self.assertEqual(self._norm(db["invoices"]), self._norm(ledger.rows.values()))
                self.assertEqual(db["payments"], 1)
                self.assertEqual(db["allocations"], len(plan.allocations))
                applied = float(self.sql("select applied_amount from bank_payments;"))
                self.assertEqual(applied, plan.applied)

    def test_stale_credit_row_rolls_everything_back(self):
        self.assert_rolled_back(
            FakeLedger([_credit(1, -1000.0), _target(2, 130.0)]),
            lambda ops: ops[0].update(expected_amount=-999.0),
        )

    def test_later_target_failing_rolls_back_the_earlier_ones(self):
        def break_second_target(ops):
            targets = [op for op in ops if op["op"] == "target_update"]
            targets[1]["expected_amount"] = 71.0
        self.assert_rolled_back(
            FakeLedger([_credit(1, -1000.0), _target(2, 130.0), _target(3, 70.0)]), break_second_target
        )

    def test_failure_creating_the_remainder_row_rolls_back(self):
        def break_remainder(ops):
            remainder = [op for op in ops if op["op"] == "insert_row" and op["row"]["paid"] == "No"][0]
            remainder["row"]["payment_amount"] = "not-a-number"
        self.assert_rolled_back(FakeLedger([_credit(1, -100.0), _target(2, 130.0)]), break_remainder)

    def test_failure_creating_the_usage_row_rolls_back(self):
        def break_usage(ops):
            usage = [op for op in ops if op["op"] == "insert_row" and op["row"]["paid"] == "Yes"][0]
            usage["row"]["payment_date"] = "2026-13-45"
        self.assert_rolled_back(FakeLedger([_credit(1, -1000.0), _target(2, 130.0)]), break_usage)

    def test_failure_saving_the_payment_record_rolls_back_everything_before_it(self):
        self.assert_rolled_back(
            FakeLedger([_credit(1, -1000.0), _target(2, 130.0)]),
            lambda ops: ops[-1]["entry"].update(payment_date="not-a-date"),
        )

    def test_failure_saving_the_allocations_rolls_back_the_payment_record_too(self):
        def break_allocation(ops):
            ops[-1]["allocations"][0]["amount_applied"] = "x"
        self.assert_rolled_back(FakeLedger([_credit(1, -1000.0), _target(2, 130.0)]), break_allocation)

    def test_cancelled_or_paid_rows_are_never_touched_by_the_function(self):
        for status in ("cancelled", "Yes", "Partial"):
            with self.subTest(status):
                ledger = FakeLedger([_credit(1, -1000.0), _target(2, 130.0)])
                payload = ledger.plan(8700).rpc_payload()
                self.seed(ledger)
                self.sql(f"update invoices set paid = '{status}' where id = 1;")  # the credit row is no longer open
                before = self.snapshot()
                with self.assertRaises(RuntimeError):
                    self.call(payload)
                self.assertEqual(self.snapshot(), before)

    def test_unknown_operation_is_rejected(self):
        self.seed(FakeLedger([_credit(1, -1000.0), _target(2, 130.0)]))
        before = self.snapshot()
        with self.assertRaises(RuntimeError):
            self.call({"ops": [{"op": "drop_everything"}]})
        self.assertEqual(self.snapshot(), before)

    def test_only_the_service_role_can_execute_the_function(self):
        def can(role):
            return self.sql(f"select has_function_privilege('{role}', 'public.apply_credit_atomic(jsonb)', 'execute');")
        self.assertEqual(can("service_role"), "t")
        self.assertEqual(can("anon"), "f")
        self.assertEqual(can("authenticated"), "f")


if __name__ == "__main__":
    unittest.main()
