-- Run this in the Supabase SQL editor (once)

create table if not exists license_change_log (
    id               bigint generated by default as identity primary key,
    changed_at       timestamptz not null default timezone('utc', now()),
    project_name     text not null,
    country          text,
    old_license_eop  date,
    new_license_eop  date,
    action           text not null default 'Updated',
    updated_by       text,
    source_name      text,
    notes            text,
    created_at       timestamptz not null default timezone('utc', now()),
    updated_at       timestamptz not null default timezone('utc', now())
);

create index if not exists license_change_log_changed_at_idx on license_change_log(changed_at desc);
create index if not exists license_change_log_project_name_idx on license_change_log(project_name);