-- Run this in Supabase SQL editor (once).
-- Tracks license-expiry alert emails so scheduled jobs do not resend the same
-- project/date/day-before alert repeatedly.

create table if not exists license_expiry_alert_log (
    id            bigint generated by default as identity primary key,
    project_name  text not null,
    license_eop   date not null,
    days_before   integer not null default 3,
    sent_to       text,
    sent_cc       text,
    sent_at       timestamptz not null default now(),
    unique (project_name, license_eop, days_before)
);

create index if not exists license_expiry_alert_log_sent_at_idx
    on license_expiry_alert_log(sent_at desc);

create index if not exists license_expiry_alert_log_license_eop_idx
    on license_expiry_alert_log(license_eop);

notify pgrst, 'reload schema';
