-- Run this in the Supabase SQL editor (once)

create table if not exists project_change_log (
    id           bigint generated by default as identity primary key,
    changed_at   timestamptz not null default timezone('utc', now()),
    project_name text not null,
    country      text,
    field_name   text not null,
    old_value    text,
    new_value    text,
    source_name  text,
    updated_by   text,
    notes        text,
    created_at   timestamptz not null default timezone('utc', now()),
    updated_at   timestamptz not null default timezone('utc', now())
);

create index if not exists project_change_log_changed_at_idx on project_change_log(changed_at desc);
create index if not exists project_change_log_project_name_idx on project_change_log(project_name);
create index if not exists project_change_log_field_name_idx on project_change_log(field_name);