-- Run this in the Supabase SQL editor (once)

create table if not exists bank_payments (
    id                  bigint generated by default as identity primary key,
    created_at          timestamptz not null default timezone('utc', now()),
    updated_at          timestamptz not null default timezone('utc', now()),
    payment_date        date,
    invoice_number      bigint,
    source_name         text,
    source_kind         text,
    payment_fingerprint text unique,
    instructed_amount   numeric(12, 2),
    received_amount     numeric(12, 2),
    applied_amount      numeric(12, 2),
    fee_amount          numeric(12, 2),
    currency            text not null default 'EUR',
    raw_text            text,
    parsed_payload      jsonb not null default '{}'::jsonb,
    notes               text
);

create index if not exists bank_payments_payment_date_idx on bank_payments(payment_date desc);
create index if not exists bank_payments_invoice_number_idx on bank_payments(invoice_number);

create table if not exists bank_payment_allocations (
    id              bigint generated by default as identity primary key,
    payment_id      bigint not null references bank_payments(id) on delete cascade,
    invoice_row_id  bigint,
    invoice_number  bigint,
    project_name    text,
    maintenance_year text,
    year            integer,
    amount_applied  numeric(12, 2),
    created_at      timestamptz not null default timezone('utc', now())
);

create index if not exists bank_payment_allocations_payment_id_idx on bank_payment_allocations(payment_id);
create index if not exists bank_payment_allocations_invoice_row_id_idx on bank_payment_allocations(invoice_row_id);
create index if not exists bank_payment_allocations_project_name_idx on bank_payment_allocations(project_name);