-- Run this in the Supabase SQL editor (once)

create table if not exists sent_invoices (
    id                bigint generated by default as identity primary key,
    sent_at           timestamptz not null default timezone('utc', now()),
    invoice_number    bigint,
    month             text,
    year              integer,
    pdf_filename      text,
    pdf_archive_path  text,
    pdf_storage_bucket text,
    pdf_storage_path  text,
    recipients        jsonb not null default '[]'::jsonb,
    cc                jsonb not null default '[]'::jsonb,
    subject           text,
    project_count     integer,
    total_amount      numeric(12, 2),
    saved_to_ledger   boolean not null default false,
    ledger_rows_added integer,
    source_name       text,
    created_at        timestamptz not null default timezone('utc', now()),
    updated_at        timestamptz not null default timezone('utc', now())
);

create index if not exists sent_invoices_sent_at_idx on sent_invoices(sent_at desc);
create index if not exists sent_invoices_invoice_number_idx on sent_invoices(invoice_number);
create index if not exists sent_invoices_year_month_idx on sent_invoices(year, month);